# Generated by Django 3.0.7 on 2020-06-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesviews',
            options={'verbose_name': 'User History - Article view', 'verbose_name_plural': 'User History - Articles views'},
        ),
    ]
