# Generated by Django 3.0.7 on 2020-06-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesviews',
            options={'verbose_name': 'Article view', 'verbose_name_plural': 'Articles views'},
        ),
        migrations.RenameField(
            model_name='articlesviews',
            old_name='articles',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='articlesviews',
            name='updated',
        ),
    ]
