# Generated by Django 3.0.7 on 2020-06-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200630_1030'),
        ('users', '0002_auto_20200625_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'verbose_name': 'User History - Course view',
                'verbose_name_plural': 'User History - Courses views',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='viewed_courses',
            field=models.ManyToManyField(through='users.CoursesViews', to='courses.Courses'),
        ),
    ]
