# Generated by Django 3.0.7 on 2020-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200630_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesviews',
            options={'verbose_name': 'Article view', 'verbose_name_plural': 'Articles views'},
        ),
        migrations.AlterModelOptions(
            name='coursesviews',
            options={'verbose_name': 'Course view', 'verbose_name_plural': 'Courses views'},
        ),
    ]
