# Generated by Django 3.1.4 on 2020-12-04 10:31

from django.db import migrations, models
import hitcount.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.TextField()),
                ('search', models.CharField(default='', editable=False, max_length=472)),
                ('slug', models.SlugField(editable=False, max_length=150)),
                ('author', models.CharField(default='', editable=False, max_length=64)),
                ('approved', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Discussions',
                'verbose_name_plural': 'Discussion',
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
