# Generated by Django 3.1.4 on 2021-02-27 13:31

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
