# Generated by Django 3.0.7 on 2020-06-29 13:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='modules',
            name='module',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
