# Generated by Django 3.0.7 on 2020-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200629_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Modules'),
        ),
    ]
