# Generated by Django 3.1.4 on 2021-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210227_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module',
            field=models.TextField(),
        ),
    ]
