# Generated by Django 3.0.7 on 2020-06-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200629_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='module',
        ),
    ]
