# Generated by Django 3.0.7 on 2020-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200630_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='modules',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
