# Generated by Django 3.0.7 on 2020-07-02 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200701_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='order',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
