# Generated by Django 3.1.4 on 2021-02-25 23:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
