# Generated by Django 3.0.4 on 2020-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
