# Generated by Django 3.0.7 on 2020-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200625_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='use_image_as_background_in_article',
            field=models.BooleanField(default=True),
        ),
    ]
