# Generated by Django 3.1.4 on 2021-02-26 13:19

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210226_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
