# Generated by Django 3.0.7 on 2020-06-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_use_image_as_background_in_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescategories',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Articles Categories'},
        ),
    ]
