# Generated by Django 3.0.7 on 2020-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200629_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='articles',
            name='search',
            field=models.CharField(default='', editable=False, max_length=366),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
