# Generated by Django 3.1.4 on 2021-02-27 17:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=django_quill.fields.QuillField(),
        ),
    ]
