# Generated by Django 3.0.7 on 2020-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200701_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='search',
            field=models.CharField(default='', editable=False, max_length=472),
        ),
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
