# Generated by Django 3.0.7 on 2020-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200701_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
