# Generated by Django 3.1.7 on 2021-03-02 23:03

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210228_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
