# Generated by Django 3.0.4 on 2020-03-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
