# Generated by Django 3.1.7 on 2021-03-03 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20210303_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='subcomments',
            name='author_image',
        ),
        migrations.AlterField(
            model_name='comments',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
