# Generated by Django 3.0.4 on 2020-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_image',
            field=models.ImageField(blank=True, default='', upload_to='Comments_Author_Images'),
        ),
    ]
