# Generated by Django 3.0.4 on 2020-04-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_comments_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('author_image', models.ImageField(blank=True, default='', upload_to='Comments_Author_Images')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Comments')),
            ],
            options={
                'verbose_name': 'Subcomment',
                'verbose_name_plural': 'Subcomments',
            },
        ),
    ]
