# Generated by Django 2.1.15 on 2020-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_subcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
