# Generated by Django 2.1.15 on 2020-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_articlescategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescategories',
            options={'verbose_name': 'Articles Category', 'verbose_name_plural': 'Articles Categories'},
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
