# Generated by Django 2.1.15 on 2020-04-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='search',
            field=models.CharField(default='', editable=False, max_length=512),
        ),
    ]
