# Generated by Django 2.1.15 on 2020-04-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articles_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
