# Generated by Django 2.1.15 on 2020-06-18 22:54

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_articlescategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='Articles_Categories_Images'),
        ),
    ]
